/**
 * @file main.c
 * @author Jean-Sebastien Dery (260430688) and Matthew Johnston (260349319)
 * @version 1.0
 * @date November 6th 2013
 * @brief This C file will contain all the main flow of the program and the initialization of all the threads.
*/

#include "arm_math.h"
#include "stm32f4xx.h"
#include "cmsis_os.h"
#include <stdio.h>
#include "stm32f4xx.h"
#include "stm32f4xx_conf.h"
#include "stm32f4_discovery_lis302dl.h"
#include "timerManager.h"
#include "finiteStateMachine.h"
#include "lcdManager.h"
#include "servoManager.h"

// Resources:
// http://mbed.org/handbook/CMSIS-RTOS

void fsmThread(void const *argument);
void wifiThread(void const *argument);

void preamble(void);

osThreadDef(fsmThread, osPriorityNormal, 1, 0);
osThreadDef(wifiThread, osPriorityNormal, 1, 0);

osThreadId tid_fsmThread, tid_wikiThread;

/**
 @brief Program entry point
 */
int main(void) {
	preamble();
}

/**
 * Handles the interrupts generated by the TIM2 timer, which correspond to when the FSM is being processed.
*/
void TIM2_IRQHandler() {
	// Clears the interrupt flag since we are caching it right now.
	TIM_ClearITPendingBit(TIM2, TIM_IT_Update);
	osSignalSet(tid_fsmThread, 1);
}

/**
 *  Handles the interrupts generated by the TIM2 timer, which correspond to when the FSM is being processed.
*/
void TIM3_IRQHandler() {
	// Clears the interrupt flag since we are caching it right now.
	TIM_ClearITPendingBit(TIM3, TIM_IT_Update);
	osSignalSet(tid_wikiThread, 2);
}

/**
 * Main's preamble where are the initializations are done.
*/
void preamble(void) {
	initializeFSM();
	initializeServoMotors();
	initializeTIM2Timer();
	initializeTIM3Timer();
	
	tid_fsmThread = osThreadCreate(osThread(fsmThread), NULL);
}

/**
 * Defines the main thread that will process the continuous run.
*/
void fsmThread(void const *argument) {
	// Fetches the data from the temperature sensor.
	while (1){
		osSignalWait(1, osWaitForever);
		processCurrentState();
	}
}

/**
 * Defines the main thread that will process the data retrieval on wiki.
*/
void wifiThread(void const *argument) {
	// Fetches the data from the temperature sensor.
	while (1){
		osSignalWait(1, osWaitForever);
	}
}
