/**
 * @file main.c
 * @author Jean-Sebastien Dery (260430688) and Matthew Johnston (260349319)
 * @version 1.0
 * @date November 6th 2013
 * @brief This C file will contain all the main flow of the program and the initialization of all the threads.
*/

#include "arm_math.h"
#include "stm32f4xx.h"
#include "cmsis_os.h"
#include <stdio.h>
#include "stm32f4xx.h"
#include "stm32f4xx_conf.h"
#include "stm32f4_discovery_lis302dl.h"
#include "timerManager.h"
#include "finiteStateMachine.h"
#include "ledManager.h"
#include "servoManager.h"

// Resources:
// http://mbed.org/handbook/CMSIS-RTOS

/**
 @brief Thread that will perform the readings on 
 @param argument Unused
 */
void mainThread(void const *argument);

void preamble();

osThreadDef(mainThread, osPriorityNormal, 1, 0);

osThreadId tid_mainThread;

/**
 @brief Program entry point
 */
int main(void) {
	preamble();
}

/**
 * Handles the interrupts generated by the TIM2 timer.
*/
void TIM2_IRQHandler() {
	// Clears the interrupt flag since we are caching it right now.
	TIM_ClearITPendingBit(TIM2, TIM_IT_Update);
	osSignalSet(tid_mainThread, 1);
}

/**
 * Main's preamble where are the initializations are done.
*/
void preamble() {
	initializeFSM();
	initializeServoMotors();
	// Initializes the TIM2 timer so that it controls the frequency at which the main will be executed.
	initializeTIM2Timer();
	
	tid_mainThread = osThreadCreate(osThread(mainThread), NULL);
}

/**
 * Defines the main thread that will process the continuous run.
*/
void mainThread(void const *argument) {
	// Fetches the data from the temperature sensor.
	while (1){
		osSignalWait(1, osWaitForever);
		processCurrentState();
	}
}